servicos/servicos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
   path('servicosapp/', include('servicosapp.urls')),
   path('admin/', admin.site.urls),
]

servicos/servicosapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'servicosapp'
urlpatterns = [
   path('', views.index, name='index'),
   path('servicos/', views.index_servicos, name="index_servicos"),
   path('servicos/criar/', views.criar_servicos, name="criar_servicos"),
   path('servicos/criar/sucesso/', views.sucesso, name="sucesso"),
   path('servicos/<int:pk>/detalhes/', views.DetailView.as_view(), name="detalhes_servicos"),
   path('servicos/<int:id_servico>/excluir/', views.excluir_servico, name="excluir_servico"),
   path('servicos/<pk>/editar/', login_required(views.EditarForm.as_view(), login_url="/servicosapp/usuario/entrar"), name="editar_form"),
   path('usuario/cadastrar/', views.cadastrar_form, name="cadastrar_form"),
   path('usuario/entrar/', views.entrar_form, name='entrar_form'),
   path('usuario/sair/', views.sair, name="sair"),
   path('servicos/buscar/', views.buscar, name='buscar'),
   path('servicos/usuario/meus_servicos/', views.meus_servicos, name='meus_servicos'),
]

servicos/servicosapp/models.py
import django
from django.db import models
from django.contrib.auth import get_user_model

# Pegando a model do usuário
auth_user = get_user_model()

# Create your models here.
class Categoria(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nome_categoria = models.CharField(max_length=150)

    def __str__(self):
        return self.nome_categoria
    
class Estado(models.Model):
    id_estado = models.AutoField(primary_key=True)
    nome_estado = models.CharField(max_length=150)

    def __str__(self):
        return self.nome_estado

class Servico(models.Model):
    id_servico = models.AutoField(primary_key=True)
    fk_usuario = models.ForeignKey(auth_user, on_delete=models.DO_NOTHING, null=True)
    fk_categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True)
    fk_estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=150, null=False)
    descricao = models.CharField(max_length=150, default=None)
    email = models.CharField(max_length=150, null=False)
    telefone_1 = models.CharField(max_length=50, null=True)
    telefone_2 = models.CharField(max_length=50, null=True)
    preco = models.IntegerField(default=0, null=True)
    data_pub = models.DateTimeField("Data de publicação", default=django.utils.timezone.now, null=True)

    def __str__(self):
        return self.titulo

servicos/servicosapp/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.forms import ModelForm
from django.views import generic
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from . models import Servico, Categoria, Estado

def index(request):
       servicos = Servico.objects.order_by("-data_pub")[:15]
       servicos_aleatorios = Servico.objects.order_by("?")[:15]

       return render(request, 'servicosapp/index.html', {'servicos': servicos, 'servicos_aleatorios': servicos_aleatorios, 'estados': Estado.objects.all()})

def index_servicos(request):
       servicos = Servico.objects.all()
       estados = Estado.objects.all()

       context = {
              'servicos': servicos,
              'estados': estados
       }
       return render(request, 'servicosapp/servicos/index.html', context)

@login_required(login_url="/servicosapp/usuario/entrar")
def meus_servicos(request):

       current_user = request.user
       meus_servicos = Servico.objects.filter(fk_usuario = current_user.id)

       # Pegar aqui os objetos do DB que tem fk_usuario = request.user
       context = {
            'current_user': current_user,
            'meus_servicos': meus_servicos
       }

       return render(request, 'servicosapp/usuario/meus_servicos.html', context)

@login_required(login_url="/servicosapp/usuario/entrar")
def criar_servicos(request):
       categorias = Categoria.objects.all()
       estados = Estado.objects.all()

       usuario_atual = request.user
       u = User.objects.get(pk=usuario_atual.id)

       if request.method == "POST":
              categoria = request.POST['categoria']
              estado = request.POST['estado']
              c = Categoria.objects.get(nome_categoria=categoria)
              m = Estado.objects.get(nome_estado=estado)

              f = ServicosForm(request.POST)
              servico_novo = f.save()

              servico_novo.fk_usuario = u
              servico_novo.save()

              servico_novo.fk_categoria_id = c
              servico_novo.save()

              servico_novo.fk_estado_id = m
              servico_novo.save()

              HttpResponseRedirect('servicosapp/servicos/index.html')

       return render(request, 'servicosapp/servicos/criar.html', {'form': ServicosForm(), 'categorias': categorias, 'estados': estados})

class ServicosForm(ModelForm):
       class Meta:
              model = Servico
              fields = ['titulo', 'descricao', 'email', 'telefone_1', 'telefone_2', 'preco']
              
def sucesso(request):
       return render(request, "servicosapp/servicos/sucesso.html")

class DetailView(generic.DetailView):
    model = Servico
    template_name = 'servicosapp/servicos/detalhes.html'

@login_required(login_url="/servicosapp/usuario/entrar")
def excluir_servico(request, id_servico):
       servico = get_object_or_404(Servico, pk=id_servico)
       servico.delete()

       return render(request, 'servicosapp/servicos/excluir.html', {'id_servico': id_servico, 'servico': servico})

class EditarForm(generic.UpdateView):
       model = Servico
       fields = ['titulo', 'descricao', 'email', 'telefone_1', 'telefone_2', 'preco']
       template_name = "servicosapp/servicos/editar.html"
       success_url ="/servicosapp/servicos/usuario/meus_servicos"

def cadastrar_form(request):
       if request.method == 'POST':
              primeiro_nome = request.POST['primeiro_nome']
              ultimo_nome = request.POST['ultimo_nome']
              usuario = request.POST['usuario']
              email = request.POST['email']
              senha = request.POST['senha']

              try:
                     new_user = User.objects.create_user(f"{usuario}", f"{email}", f"{senha}")
                     new_user.first_name = primeiro_nome
                     new_user.last_name = ultimo_nome
                     new_user.date_joined = timezone.now()
                     #new_user.get_username
                     new_user.save()


              except IntegrityError:
                     # Tratar isso aqui na fase de testes
                     pass

       return render(request, 'servicosapp/usuario/cadastrar.html')

def entrar_form(request):

       if request.method == 'POST':
              usuario = request.POST['usuario']
              senha = request.POST['senha']

              user = authenticate(request, username=usuario, password=senha)
              if user is not None:
                     login(request, user)
                     return HttpResponseRedirect(reverse('servicosapp:index'))
                     
              else:
                     # Tratar esse erro também na fase de testes
                     pass

       return render(request, 'servicosapp/usuario/entrar.html')

def sair(request):
       logout(request)
       return redirect('servicosapp:index')

def buscar(request):
       query_check = request.GET.get('titulo')
       query_estado = request.GET.get('filtro-estado')

       if not query_check:
              pass
       
       else:
              servicos = Servico.objects.filter(titulo__icontains = query_check)

              context = {
                     'query_check': query_check,
                     'servicos': servicos,
              }
              return render(request, 'servicosapp/servicos/buscar.html', context)
       
       if not query_estado:
              pass
       else:
              se = Estado.objects.get(nome_estado = query_estado)
              estados = Servico.objects.filter(fk_estado = se.id_estado)

              context = {
                     'query_estado': query_estado,
                     'estados': estados
              }
              return render(request, 'servicosapp/servicos/buscar.html', context) 

       return render(request, 'servicosapp/servicos/buscar.html')

servicos/servicosapp/templates/base.html
{% load static %}

<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Encontre serviços diversos">
    <meta name="keywords" content="Encontre serviços diversos">
    <meta name="author" content="Rafael N">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Encontre serviços {% endblock title %}</title>

    <!-- Swiper -->
    <link href="
    https://cdn.jsdelivr.net/npm/swiper@9.1.0/swiper-bundle.min.css
    " rel="stylesheet">

    <!-- Materialize -->
    <link rel="stylesheet" href="{% static 'materialize.css' %}">
    <link rel="stylesheet" href="{% static 'servicosapp/stylesheet.css' %}" />

</head>

<body>

    {% include 'navbar.html' %}
    <main>
        {% block content %}{% endblock content %}

        <div class="fixed-action-btn">
            <a style="background-color: var(--accent-color);" class="btn-floating btn-large"
                href="{% url 'servicosapp:index' %}">
                <img src="{% static 'servicosapp/images/homeicon.png' %}" />
            </a>
        </div>

    </main>

    <footer class="page-footer">
        <div class="container"><!-- background: none !important; text-align: center; -->
            <ul>
                <li><a href="{% url 'servicosapp:index' %}">Homepage</a></li>
                <li><a href="{% url 'servicosapp:index_servicos' %}">Serviços</a></li>
            </ul>

        </div>
        </div>
        </div>

        <div class="fc footer-copyright">
            <div class="container">
                © 2023 por Rafael N
            </div>
        </div>

    </footer>

    <script src="https://cdn.jsdelivr.net/npm/swiper@9.1.0/swiper-bundle.min.js"></script>
    <script type="text/javascript" src="{% static 'materialize.js' %}" async></script>
</body>

servicos/servicosapp/templates/navbar.html
<nav>
    <div class="nav-wrapper">
        <ul id="nav-mobile" class="right">
            {% if user.is_authenticated %}
            <li style="color: black;">Olá {{ user.username }} </li>
            <li><a href="{% url 'servicosapp:sair' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'servicosapp:entrar_form' %}">Entrar</a></li>
            {% endif %}

            <li><a class="login-btn waves-effect waves-light btn"
                    href="{% url 'servicosapp:meus_servicos' %}">Meus serviços</a></li>
        </ul>
    </div>
</nav>

servicos/servicosapp/templates/searchbar.html
<form method="get" action="{% url 'servicosapp:buscar' %}">
    {% csrf_token %}
    <div class="container row z-depth-4">
        <input minlength="4" value="{{ request.get.name }}" name="titulo" placeholder="Encanemento" id="searchbar"
            type="text"></input>
    </div>
    <button disabled id="sbtn" type="submit" class="submit-btn waves-effect waves-light btn-large">Buscar</button>
</form>

<script>
    var btn = document.getElementById('sbtn');
    var searchBar = document.getElementById('searchbar');

    const testaNulo = () => {
        if(searchBar.value !== "" && searchBar.value.length >= 4) {
            btn.disabled = false;
        } else {
            btn.disabled = true;
        }
    }

    searchBar.addEventListener('input', () => testaNulo())
</script>

servicos/servicosapp/templates/servicosapp/index.html
{% extends "base.html" %}

{% block content %}
<h3>Serviços</h3>

{% include "searchbar.html" %}

<!-- Demo styles -->
<style>
    .swiper {
        margin-top: 3em;
    }

    .swiper-slide {
        text-align: center;
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: snow;
        min-width: fit-content;
    }

    .swiper-pagination-bullet-active {
        background-color: snow !important;
    }
</style>

<!-- Filtros -->
<div style="background-color: var(--accent-color); margin: 4em auto 0 auto;" class="container card-panel">
    <!-- Filtrando por estado -->
    <form method="get" action="{% url 'servicosapp:buscar' %}">
        {% csrf_token %}
        {% for estado in estados %}
        <label>
            <input value="{{ estado }}" name="filtro-estado" type="radio" checked />
            <span style="color: snow;">{{ estado }}</span>
        </label>
        {% endfor %}
        <div class="row" style="display: flex; justify-content: center;">
            <button style="font-weight: bold; color: black; min-width: fit-content;" type="submit"
                class="waves-effect waves-light btn-small white">Filtrar</button>
        </div>
    </form>

</div>
<!--  -->

<!-- Swiper -->
<br />
<br />
<br />
<br />
<br />
<br />

<!-- Lista de publicados recentemente -->
<h5 style="text-align: center; font-weight: 900;">Publicados recentemente</h5>

<div class="swiper mySwiper card-panel" style="background-color: var(--accent-color);">
    <div class="swiper-wrapper">
        {% for servico in servicos %}
        <div class="swiper-slide card-panel">
            <div class="row">
                <div class="col">
                    <div>
                        <ul>
                            <a href="{% url 'servicosapp:detalhes_servicos' servico.id_servico %}">
                                <h5>{{ servico }}</h5>
                            </a>
                            <li>Email para contato: {{ servico.email }}</li>
                            <li>Preço: R${{ servico.preco }}.00</li>
                            <li>Publicado: {{ servico.data_pub }}</li>
                            <br />
                            <span
                                style="opacity: 80%; background-color: #192a8d; border-radius: 2em; padding: 7px; font-size: smaller; font-weight: bold; border: solid 2px #758aff; color: #758aff; margin-left: auto; margin-right: auto; max-width: fit-content;">Localizado
                                em: {{ servico.fk_estado }}</span>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
</div>

<br />
<br />
<br />
<br />

<!-- Lista de publicados aleatoriamente -->
<h5 style="text-align: center; font-weight: 900;">Outros serviços</h5>

<div class="swiper mySwiper card-panel" style="background-color: var(--accent-color);">
    <div class="swiper-wrapper">
        {% for servico in servicos_aleatorios %}
        <div class="swiper-slide card-panel">
            <div class="row">
                <div class="col">
                    <div>
                        <ul>
                            <a href="{% url 'servicosapp:detalhes_servicos' servico.id_servico %}">
                                <h5>{{ servico }}</h5>
                            </a>
                            <li>Email para contato: {{ servico.email }}</li>
                            <li>Preço: R${{ servico.preco }}.00</li>
                            <li>Publicado: {{ servico.data_pub }}</li>
                            <br />
                            <span
                                style="opacity: 80%; background-color: #192a8d; border-radius: 2em; padding: 7px; font-size: smaller; font-weight: bold; border: solid 2px #758aff; color: #758aff; margin-left: auto; margin-right: auto; max-width: fit-content;">Localizado
                                em: {{ servico.fk_estado }}</span>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
</div>


<!-- Swiper JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->
<script>
    var swiper = new Swiper(".mySwiper", {
        slidesPerView: 3,
        spaceBetween: 30,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
    });
</script>

{% endblock content %}

servicos/servicosapp/templates/servicosapp/servicos/buscar.html
{% extends 'base.html' %}

<title>{% block title %}Buscando serviço de {{ query_check }} {% endblock title %}</title>

{% block content %}
<h3>Resultado da pesquisa: </h3>

{% if servicos %}
<div style="margin-top: 4em; display: flex; justify-content: center; align-items: center;">

    <div style="text-align: center;" class="container row">

        {% for servico in servicos %}
        <ul class="card-panel indigo lighten-5">
            <a id="ancora-servicos" href="{% url 'servicosapp:detalhes_servicos' servico.id_servico %}">
                <h5 style="font-weight: bolder;">{{ servico }}</h5>
            </a>
            <li>Email para contato: {{ servico.email }}</li>
            <li>Preço: R${{ servico.preco }}.00</li>
            <br />
            <span
                style="opacity: 80%; background-color: #192a8d; border-radius: 2em; padding: 7px; font-size: smaller; font-weight: bold; border: solid 2px #758aff; color: #758aff; margin-left: auto; margin-right: auto; max-width: fit-content;">Localizado
                em: {{ servico.fk_estado }}</span>
        </ul>

        {% endfor %}
    </div>
</div>

{% else %}
{% endif %}

{% if estados %}
<div style="margin-top: 4em; display: flex; justify-content: center; align-items: center;">

    <div style="text-align: center;" class="container row">

        {% for estado in estados %}
        <ul class="card-panel indigo lighten-5">
            <a id="ancora-servicos" href="{% url 'servicosapp:detalhes_servicos' estado.id_servico %}">
                <h5 style="font-weight: bolder;">{{ estado }}</h5>
            </a>
            <li>Email para contato: {{ estado.email }}</li>
            <li>Preço: R${{ estado.preco }}.00</li>
            <br />
            <span
                style="opacity: 80%; background-color: #192a8d; border-radius: 2em; padding: 7px; font-size: smaller; font-weight: bold; border: solid 2px #758aff; color: #758aff; margin-left: auto; margin-right: auto; max-width: fit-content;">Localizado
                em: {{ estado.fk_estado }}</span>
        </ul>

        {% endfor %}
    </div>
</div>

{% else %}
{% endif %}

{% endblock content %}

servicos/servicosapp/templates/servicosapp/servicos/criar.html
{% extends "base.html" %}

<title>{% block title %} Cadastre um serviço {% endblock title %}</title>

{% block content %}
<h3>Cadastre seu serviço</h3>
<form id="dfd" class="container" action="{% url 'servicosapp:criar_servicos' %}" method="post">
    {% csrf_token %}

    {{ form }}

    <!-- Select de categorias -->
    <label for="categoria">Escolha uma categoria para seu serviço:</label>
    <input required list="categorias" name="categoria" id="categoria">

    <datalist id="categorias">
        {% for categoria in categorias %}
        <option value="{{ categoria }}">
        {% endfor %}
    </datalist>

    <!-- Select de estados -->
    <label for="estado">Em qual estado você presta esse serviço?</label>
    <input required list="estados" name="estado" id="estado">

    <datalist id="estados">
        {% for estado in estados %}
            <option value="{{ estado }}">
        {% endfor %}
    </datalist>

    <button style="margin-top: 3em;" class="waves-effect waves-light btn-large submit-btn" type="submit"
        value="Enviar">Enviar</button>
</form>

{% endblock content %}

servicos/servicosapp/templates/servicosapp/servicos/editar.html
{% extends "base.html" %}

<title>{% block title %}Editar serviço{% endblock title %}</title>

{% block content %}
<h3>Editar serviço</h3>

<form class="container" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button style="margin-top: 1em;" class="waves-effect waves-light btn-large submit-btn" type="submit"
        value="Enviar">Alterar</button>
</form>

{% endblock content %}

servicos/servicosapp/templates/servicosapp/servicos/excluir.html
{% extends "base.html" %}

<title>{% block title %}Excluir{% endblock title %}</title>

{% block content %}
<div class="container" style="text-align: center;">
    <div class="row">
        <h4>{{ servico }} excluído com sucesso! </h4>
        <p>Redirecionando... </p>
    </div>
    <div class="preloader-wrapper big active">
        <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div>
            <div class="gap-patch">
                <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
</div>
<script>
window.location.href = "/servicosapp/servicos"
</script>
{% endblock content %}

servicos/servicosapp/templates/servicosapp/servicos/index.html
{% extends 'base.html' %}

{% block content %}
<h3>Serviços</h3>

{% include "searchbar.html" %}

<!-- Filtros -->
<div style="background-color: var(--accent-color); margin: 4em auto 0 auto;" class="container card-panel">
    <!-- Filtrando por estado -->
    <form method="get" action="{% url 'servicosapp:buscar' %}">
        {% csrf_token %}
        {% for estado in estados %}
        <label>
            <input value="{{ estado }}" name="filtro-estado" type="radio" checked />
            <span style="color: snow;">{{ estado }}</span>
        </label>
        {% endfor %}
        <div class="row" style="display: flex; justify-content: center;">
            <button style="font-weight: bold; color: black; min-width: fit-content;" type="submit"
                class="waves-effect waves-light btn-small white">Filtrar</button>
        </div>
    </form>

</div>
<!--  -->

<div style="margin-top: 4em; display: flex; justify-content: center; align-items: center;">
    {% if servicos %}
    <div style="text-align: center;" class="container row">
        {% for servico in servicos %}
        <ul class="card-panel indigo lighten-5">
            <a id="ancora-servicos" href="{% url 'servicosapp:detalhes_servicos' servico.id_servico %}">
                <h5 style="font-weight: bolder;">{{ servico }}</h5>
            </a>
            <li>Email para contato: {{ servico.email }}</li>
            <li>Preço: R${{ servico.preco }}.00</li>
            <br />
            <span
                style="opacity: 80%; background-color: #192a8d; border-radius: 2em; padding: 7px; font-size: smaller; font-weight: bold; border: solid 2px #758aff; color: #758aff; margin-left: auto; margin-right: auto; max-width: fit-content;">Localizado
                em: {{ servico.fk_estado }}</span>
        </ul>

        {% endfor %}
    </div>
</div>

{% else %}
<p style="text-align: center; margin-top: 4em;"></p>
{% endif %}

{% endblock content %}

servicos/servicosapp/templates/servicosapp/servicos/sucesso.html
{% extends "base.html" %}

{% block content %}
<h3>Operação concluída com sucesso!</h3>
{% endblock content %}

servicos/servicosapp/templates/servicosapp/usuario/cadastrar.html
{% extends "base.html" %}

{% block content %}
<h3>Cadastrar</h3>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}

<form style="margin-left: auto; margin-right: auto; margin-top: 6em;" class="container card-panel" method="post"
    action="{% url 'servicosapp:cadastrar_form' %}">
    {% csrf_token %}
    <table>
        <tr>
            <label for="primeiro_nome">Primeiro Nome: </label>
            <input minlength="3" required name="primeiro_nome" id="primeiro_nome" placeholder="John"></input>
        </tr>
        <tr>
            <label for="ultimo_nome">Último Nome: </label>
            <input minlength="3" required name="ultimo_nome" id="ultimo_nome" placeholder="Doe"></input>
        </tr>
        <tr>
            <label>Usuário: </label>
            <input minlength="6" required name="usuario" id="usuario" placeholder="johndoe5"></input>
        </tr>
        <tr>
            <label for="email">Email: </label>
            <input required name="email" id="email" placeholder="johndoe@mail.com"></input>
        </tr>
        <tr>
            <label for="senha">Senha: </label>
            <input type="password" minlength="8" required name="senha" id="senha" placeholder="********"></input>
        </tr>

        <tr>
            <label for="confirma-senha">Confirmar senha: </label>
            <input type="password" minlength="8" required name="confirma-senha" id="confirma-senha"
                placeholder="********"></input>
        </tr>

        {# Aqui tem que adicionar campo de confirmar senha #}

    </table>

    <button disabled id="sbtn" style="margin-top: 1em;" class="waves-effect waves-light btn-large submit-btn"
        type="submit">Cadastrar</button>
    <input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}


<script async>
var testeCondicional = () => confirmaSenha.value == senha.value? sBtn.disabled = false: sBtn.disabled = true;
// Variável representando o input de senha
var senha = document.getElementById('senha');
senha.addEventListener('input', async() => testeCondicional());

// Variável representando o input de confirmar senha
var confirmaSenha = document.getElementById('confirma-senha');
confirmaSenha.addEventListener('input', async() => testeCondicional());

// Agora a gente pega o botão de submit
var sBtn = document.getElementById('sbtn');
</script>
{% endblock %}

servicos/servicosapp/templates/servicosapp/usuario/entrar.html
{% extends "base.html" %}

{% block content %}
<h3>Entrar</h3>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}

<form style="margin-left: auto; margin-right: auto; margin-top: 6em;" class="container card-panel" method="post" action="{% url 'servicosapp:entrar_form' %}">
    {% csrf_token %}
    <table>
        <tr>
            <label>Usuário: </label>
            <input minlength="6" required name="usuario" id="usuario"></input>
        </tr>
        <tr>
            <label for="senha">Senha: </label>
            <input type="password" minlength="8" required name="senha" id="senha"></input>
        </tr>
    </table>

    <button style="margin-top: 1em;" class="waves-effect waves-light btn-large submit-btn" type="submit">Entrar</button>
    <input type="hidden" name="next" value="{{ next }}">
    <a style="display: flex; justify-content: center;padding: 2em;" href="{% url 'servicosapp:cadastrar_form' %}">Criar conta</a>

</form>

{# Assumes you set up the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Esqueceu sua senha?</a></p> #}

{% endblock %}

servicos/servicosapp/templates/servicosapp/usuario/meus_servicos.html
{% extends 'base.html' %}

{% block content %}
<h3>Meus serviços</h3>

<a style="background-color: var(--accent-color); max-width: max-content; text-decoration: none; display: block; margin-left: auto; margin-right: auto;"
    class="link-btn waves-effect waves-light btn-large" href="{% url 'servicosapp:criar_servicos' %}">Criar serviço</a>

{% if meus_servicos %}
<div class="card-panel" style="margin-top: 2em; display: flex; justify-content: center; align-items: center;">
    <ul>
        {% for meu_servico in meus_servicos %}
        <a id="ancora-servicos" href="{% url 'servicosapp:detalhes_servicos' meu_servico.id_servico %}">
            <h5>{{ meu_servico.titulo }}</h5>
        </a>
        <li>Email para contato: {{ meu_servico.email }}</li>
        <li>Preço: R${{ meu_servico.preco }}.00</li>
        <li><small>Publicado em: {{ meu_servico.data_pub }}</small></li>

        <a href="/servicosapp/servicos/{{ meu_servico.id_servico }}/editar/">Editar</a>
        |
        <a style="cursor: pointer;" id="excluir-btn"
            href="/servicosapp/servicos/{{ meu_servico.id_servico }}/excluir/">Excluir</a>

        <div class="section"></div>
        <div class="divider"></div>

        {% endfor %}
    </ul>

</div>

{% else %}
<p style="text-align: center; margin-top: 4em;">Não há serviços cadastrados!</p>
{% endif %}

{% endblock content %}